<?php

/**
 * Created by PhpStorm.
 * User: roberto
 * Date: 30/07/15
 * Time: 15.10
 */
class copyAllSource2TargetController extends ajaxController {

    private $id_job;
    private $pass;

    protected function __construct() {
        parent::__construct(); // TODO: Change the autogenerated stub

        $filterArgs = array(
                'id_job' => array(
                        'filter' => FILTER_SANITIZE_NUMBER_INT
                ),
                'pass'   => array(
                        'filter' => FILTER_SANITIZE_STRING,
                        'flags'  => FILTER_FLAG_STRIP_LOW | FILTER_FLAG_STRIP_HIGH
                ),
        );

        $postInput = filter_input_array( INPUT_POST, $filterArgs );

        $this->id_job = $postInput[ 'id_job' ];
        $this->pass   = $postInput[ 'pass' ];

        if ( empty( $this->id_job ) ) {
            Log::doLog( __CLASS__ . " --> Empty id job" );
            $this->result[ 'errors' ] = array(
                    'code'    => -1,
                    'message' => "Empty id job."
            );

        }
        if ( empty( $this->pass ) ) {
            Log::doLog( __CLASS__ . " --> Empty job password" );
            $this->result[ 'errors' ] = array(
                    'code'    => -2,
                    'message' => "Empty job password."
            );
        }
    }


    /**
     * When Called it perform the controller action to retrieve/manipulate data
     *
     * @return mixed
     */
    function doAction() {
        if ( !empty( $this->result[ 'errors' ] ) ) {
            return;
        }

        $job_data = getJobData( $this->id_job, $this->pass );

        if ( empty( $job_data ) ) {
            Log::doLog( __CLASS__ . " --> Wrong id_job-password couple. Job not found." );
            $this->result[ 'errors' ] = array(
                    'code'    => -3,
                    'message' => "Wrong id_job-password couple. Job not found."
            );

            return;
        }

        $first_seg = $job_data[ 'job_first_segment' ];
        $last_seg  = $job_data[ 'job_last_segment' ];

        $affected_rows = self::copySegmentInTranslation( $first_seg, $last_seg );

        $this->result['data'] = array(
            'code' => 1,
            'segments_modified' => $affected_rows
        );
    }


    /**
     * Copies the segments.segment field into segment_translations.translation
     * and sets the segment status to DRAFT.
     * This operation is made only for the segments in NEW status
     *
     * @param $first_seg int
     * @param $last_seg  int
     */
    private static function copySegmentInTranslation( $first_seg, $last_seg ) {

        $query = "update segment_translations st
                    join segments s on st.id_segment = s.id
                    set st.translation = s.segment,
                    st.status = 'DRAFT'
                    where st.status = 'NEW'
                    and st.id_segment between %d and %d";

        $db = Database::obtain();

        $result = $db->query(
            sprintf(
                    $query,
                    $first_seg,
                    $last_seg
            )
        );

        if( $result !== true){
            return 0;
        }

        return $db->affected_rows;
    }

}