'use strict';

const {describe, it} = require('node:test');
const assert = require('node:assert/strict');
const {
    EMOJI_TYPE_MAP,
    TYPE_EMOJI_MAP,
    VALID_TYPES,
    MAX_SUBJECT_LENGTH,
    validateCommitMessage,
    findTypeForEmoji,
    isAutoGenerated,
    stripVS16,
} = require('./commit-message-check.js');

// ── stripVS16 ─────────────────────────────────────────────────

describe('stripVS16', () => {
    it('removes VS16 from string', () => {
        assert.equal(stripVS16('\u26A1\uFE0F'), '\u26A1');
    });

    it('leaves strings without VS16 unchanged', () => {
        assert.equal(stripVS16('\u2728'), '\u2728');
    });

    it('removes multiple VS16 characters', () => {
        assert.equal(stripVS16('\uFE0Fa\uFE0Fb\uFE0F'), 'ab');
    });
});

// ── findTypeForEmoji ──────────────────────────────────────────

describe('findTypeForEmoji', () => {
    it('finds type for each canonical emoji', () => {
        for (const [emoji, type] of Object.entries(EMOJI_TYPE_MAP)) {
            assert.equal(findTypeForEmoji(emoji), type, `${emoji} should map to ${type}`);
        }
    });

    it('finds type when VS16 is stripped from input', () => {
        assert.equal(findTypeForEmoji('\u26A1'), 'perf');
    });

    it('finds type when VS16 is added to input', () => {
        assert.equal(findTypeForEmoji('\u2728\uFE0F'), 'feat');
    });

    it('returns null for unknown emoji', () => {
        assert.equal(findTypeForEmoji('\u{1F600}'), null);
    });
});

// ── isAutoGenerated ───────────────────────────────────────────

describe('isAutoGenerated', () => {
    it('detects merge commit', () => {
        assert.equal(isAutoGenerated('Merge branch \'main\' into feature'), true);
    });

    it('detects merge pull request', () => {
        assert.equal(isAutoGenerated('Merge pull request #42 from org/branch'), true);
    });

    it('rejects normal message', () => {
        assert.equal(isAutoGenerated('\u2728 feat: add login'), false);
    });
});

// ── EMOJI_TYPE_MAP / TYPE_EMOJI_MAP consistency ───────────────

describe('map consistency', () => {
    it('TYPE_EMOJI_MAP is the reverse of EMOJI_TYPE_MAP', () => {
        for (const [emoji, type] of Object.entries(EMOJI_TYPE_MAP)) {
            assert.equal(TYPE_EMOJI_MAP[type], emoji);
        }
    });

    it('VALID_TYPES contains all map values', () => {
        const fromMap = Object.values(EMOJI_TYPE_MAP).sort();
        assert.deepEqual([...VALID_TYPES].sort(), fromMap);
    });

    it('has 12 type entries', () => {
        assert.equal(VALID_TYPES.length, 12);
    });
});

// ── validateCommitMessage – valid messages ────────────────────

describe('validateCommitMessage – valid', () => {
    it('simple feat', () => {
        const r = validateCommitMessage('\u2728 feat: add user login');
        assert.equal(r.valid, true);
        assert.equal(r.errors.length, 0);
        assert.equal(r.skipped, false);
    });

    it('fix with scope', () => {
        const r = validateCommitMessage('\u{1F41B} fix(auth): handle expired token');
        assert.equal(r.valid, true);
    });

    it('breaking change with !', () => {
        const r = validateCommitMessage('\u2728 feat(api)!: remove legacy endpoint');
        assert.equal(r.valid, true);
    });

    it('all 12 types accepted', () => {
        const messages = [
            ['\u{1F3D7}\uFE0F', 'build'],
            ['\u{1F527}', 'chore'],
            ['\u{1F477}', 'ci'],
            ['\u{1F4DD}', 'docs'],
            ['\u2728', 'feat'],
            ['\u{1F41B}', 'fix'],
            ['\u26A1\uFE0F', 'perf'],
            ['\u267B\uFE0F', 'refactor'],
            ['\u23EA\uFE0F', 'revert'],
            ['\u{1F484}', 'style'],
            ['\u2705', 'test'],
            ['\u{1F310}', 'i18n'],
        ];
        for (const [emoji, type] of messages) {
            const r = validateCommitMessage(`${emoji} ${type}: do something`);
            assert.equal(r.valid, true, `${emoji} ${type} should be valid`);
        }
    });

    it('merge commit is skipped', () => {
        const r = validateCommitMessage('Merge branch \'main\' into feature');
        assert.equal(r.valid, true);
        assert.equal(r.skipped, true);
        assert.equal(r.errors.length, 0);
    });

    it('multi-line message validates only subject', () => {
        const r = validateCommitMessage('\u{1F41B} fix: resolve crash\n\nDetailed body here.');
        assert.equal(r.valid, true);
    });

    it('exactly 100 characters is valid', () => {
        const desc = 'a'.repeat(100 - '\u2728 feat: '.length);
        const r = validateCommitMessage(`\u2728 feat: ${desc}`);
        assert.equal(r.valid, true);
    });

    it('emoji without VS16 matches type with VS16 in map', () => {
        const r = validateCommitMessage('\u26A1 perf: optimize query');
        assert.equal(r.valid, true);
    });

    it('emoji with VS16 matches type without VS16 in map', () => {
        const r = validateCommitMessage('\u2728\uFE0F feat: add feature');
        assert.equal(r.valid, true);
    });
});

// ── validateCommitMessage – invalid messages ──────────────────

describe('validateCommitMessage – invalid', () => {
    it('empty message', () => {
        const r = validateCommitMessage('');
        assert.equal(r.valid, false);
        assert.ok(r.errors[0].includes('Empty'));
    });

    it('null message', () => {
        const r = validateCommitMessage(null);
        assert.equal(r.valid, false);
    });

    it('undefined message', () => {
        const r = validateCommitMessage(undefined);
        assert.equal(r.valid, false);
    });

    it('no space after emoji', () => {
        const r = validateCommitMessage('\u2728feat: add login');
        assert.equal(r.valid, false);
        assert.ok(r.errors.some(e => e.includes('Format after emoji')));
    });

    it('unknown emoji', () => {
        const r = validateCommitMessage('\u{1F600} feat: add smile');
        assert.equal(r.valid, false);
        assert.ok(r.errors.some(e => e.includes('Unknown emoji')));
    });

    it('invalid type', () => {
        const r = validateCommitMessage('\u2728 feature: add login');
        assert.equal(r.valid, false);
        assert.ok(r.errors.some(e => e.includes('Invalid type')));
    });

    it('emoji-type mismatch', () => {
        const r = validateCommitMessage('\u{1F41B} feat: add login');
        assert.equal(r.valid, false);
        assert.ok(r.errors.some(e => e.includes('not "feat"')));
    });

    it('capitalized description', () => {
        const r = validateCommitMessage('\u2728 feat: Add user login');
        assert.equal(r.valid, false);
        assert.ok(r.errors.some(e => e.includes('lowercase')));
    });

    it('trailing period', () => {
        const r = validateCommitMessage('\u2728 feat: add user login.');
        assert.equal(r.valid, false);
        assert.ok(r.errors.some(e => e.includes('period')));
    });

    it('exceeds 100 characters', () => {
        const desc = 'a'.repeat(101 - '\u2728 feat: '.length);
        const r = validateCommitMessage(`\u2728 feat: ${desc}`);
        assert.equal(r.valid, false);
        assert.ok(r.errors.some(e => e.includes('exceeds')));
    });

    it('missing colon after type', () => {
        const r = validateCommitMessage('\u2728 feat add login');
        assert.equal(r.valid, false);
        assert.ok(r.errors.some(e => e.includes('Format')));
    });

    it('emoji only, no rest', () => {
        const r = validateCommitMessage('\u2728');
        assert.equal(r.valid, false);
        assert.ok(r.errors.some(e => e.includes('space')));
    });

    it('collects multiple errors', () => {
        const desc = 'A'.repeat(95);
        const r = validateCommitMessage(`\u{1F41B} feat: ${desc}.`);
        assert.equal(r.valid, false);
        assert.ok(r.errors.length >= 3, `expected >= 3 errors, got ${r.errors.length}: ${r.errors.join('; ')}`);
    });
});
