module.exports = {
  testEnvironment: 'jsdom',
  testEnvironmentOptions: {
    customExportConditions: [''],
  },
  maxWorkers: '50%',
  workerIdleMemoryLimit: '256MB',
  forceExit: true,
  setupFiles: ['<rootDir>/setupFiles.jest.js', '<rootDir>/jest.polyfills.js'],
  setupFilesAfterEnv: ['<rootDir>/setupFilesAfterEnv.jest.js'],
  collectCoverageFrom: [
    '<rootDir>/public/**/*.js',
    '!**/build/**',
    '!<rootDir>/public/api/**',
    '!<rootDir>/public/**/*.min.js',
    '!**/index.js',
    '!<rootDir>/public/js/components/icons/**',
    '!<rootDir>/public/img/icons/**',
  ],
  coverageThreshold: {
    './public/js/components/footer/': { lines: 80 },
    './public/js/components/review/': { lines: 40 },
    './public/js/components/quality_report/': { lines: 70 },
    './public/js/globalFunctions.js': { lines: 15 },
    './public/js/components/contextPreview/': { lines: 0 },
    './public/js/components/activityLog/': { lines: 0 },
    './public/js/sse/': { lines: 0 },
    './public/js/components/xliffToTarget/': { lines: 0 },
    './public/js/setTranslationUtil.js': { lines: 5 },
    './public/js/components/notificationsComponent/': { lines: 0 },
    './public/js/components/onBoarding/': { lines: 5 },
    './public/js/components/createProject/': { lines: 50 },
    './public/js/components/languageSelector/': { lines: 0 },
    './public/js/components/outsource/': { lines: 5 },
    './public/js/components/projects/': { lines: 45 },
    './public/js/components/common/': { lines: 45 },
    './public/js/components/analyze/': { lines: 0 },
    './public/js/components/review_extended/': { lines: 0 },
    './public/js/hooks/': { lines: 30 },
    './public/js/components/modals/': { lines: 5 },
    './public/js/actions/': { lines: 5 },
    './public/js/pages/': { lines: 10 },
    './public/js/utils/': { lines: 25 },
    './public/js/stores/': { lines: 5 },
    './public/js/components/header/': { lines: 10 },
    './public/js/api/': { lines: 15 },
    './public/js/components/settingsPanel/': { lines: 45 },
    './public/js/components/segments/': { lines: 20 },
  },
  roots: ['<rootDir>/public/'],
  testPathIgnorePatterns: ['/node_modules/'],
  transformIgnorePatterns: ['node_modules/(?!@bundled-es-modules)/', '.github/scripts/'],
  transform: {
    '^.+\\.js$': 'babel-jest',
    '.+\\.(css|styl|less|sass|scss)$': 'jest-transform-css',
  },
  moduleNameMapper: {
    '\\.module\\.(css|scss|sass|less)$': '<rootDir>/test-utils/cssModuleMock.js',
  },
}
