fr-FR,wrong
absorber,assorbire
Acide,Acido
Agua,Agua
Air,Air
allumer,illuminare
anticernes,antiocchiaie
anti-oxydantes,anti-ossidante
apaiser,attenuare
applicateur,applicatore
application,applicazione
appliquer,applicare
AQUA,AQUA
arcade,arcata
astringente,astringente
Astuce,Suggerimento
Autobronzant,autoabbronzante
avocat,avocado
Bad,Bad
baie,bacca
bain,bagno
balayage,"colpi di sole"
bambou,bambù
Bathina,Bathina
Baume,Balsamo
Big,Big
biseaut,obliquo
Blush,Blush
booster,stimolatore
bouton,brufolo
brillance,brillantezza
bronzage,abbronzatura
bronzant,abbronzante
brosse,spazzolino
Brosser,Spazzolare
Brow,Brow
Brume,Spray
Brush,Brush
camoufler,mimetizzare
carnations,carnagioni
cellulite,cellulite
cernes,occhiaie
chachabalm,chachabalm
chachatint,chachatint
charbonneux,smoky
chevelu,capelluto
Chlorella,Chlorella
cils,ciglia
Cleanser,Cleanser
commissures,commessure
confort,comfort
confortable,confortevole
contour,contorno
correcteur,correttore
couche,strato
coupelle,coppetta
courbure,curvatura
crayon,matita
cremeuse,cremosa
cube,cubo
cushion,cushion
cuticules,cuticole
démaquillant,struccante
démaquiller,struccare
dermatologique,dermatologico
Discipliner,Disciplinare
d'oie,"di gallina"
d'onagre,"di enotera"
douceur,delicatezza
Easy,Easy
éblouissant,abbagliante
encre,inchiostro
enlumineur,illuminante
enrichi,arricchito
épilation,depilazione
éponge,spugna
Escada,Escada
Essorez,Centrifuga
estomper,applicare
Etirer,Stendere
exfoliant,esfoliante
exfoliation,esfoliazione
extrait,estratto
Eye,Eye
eyeliner,eyeliner
fard,fard
faux-cils,"ciglia finte"
ferme,tonica
fermeté,tonicità
film,strato
fin,sottile
finitive,fissativo
fixer,fissare
flacon,flacone
flatteuse,"che si adatta a tutti i tipi"
Flawless,Flawless
floqué,floccato
fond,fondo
fondante,fondente
formule,formula
fragrance,fragranza
frictionner,frizionare
frottements,attrito
fuselé,appuntito
gel,gel
glamour,glamour
glissante,scorrevole
gloss,gloss
glycolique,glicolico
goupillon,spazzolino
grain,grana
hale,abbronzatura
Highlighting,Highlighting
Hit,Hit
houpette,piumino
houppe,piumino
hyaluronique,ialuronico
Hydra-Dose,Hydra-Dose
Hydra-Eyezone,Hydra-Eyezone
Hydra-Shock,Hydra-Shock
hydratant,idratante
hydratation,idratazione
hydrater,idratare
Hydra-Volume,Hydra-Volume
HyH2,HyH2
Ice,Ice
illuminateur,illuminante
Illuminer,Illuminare
imbiber,immergere
imperfection,imperfezione
impureté,impurità
insaponifiables,insaponificabili
interrogé,intervistato
irritation,irritazione
jojoba,jojoba
karité,karité
King,King
Kit,Kit
lacté,"di latte"
laiton,ottone
languette,linguetta
lentilles,lenti
linge,panno
lingette,salvietta
Lipstick,Lipstick
lisser,levigare
Lollibalm,Lollibalm
lotion,lozione
lumineux,luminoso
LUNA,LUNA
M-16,M-16
maquillage,make-up
maquiller,truccare
marcations,segni
mascara,mascara
masque,maschera
massage,massaggio
mat,mat
matifié,opacizzato
micellaire,micellare
mine,mine
moelleuse,morbida
moufles,muffole
moussant,schiumoso
mousse,schiuma
nacre,madreperla
nbsp,nbsp
nettoyage,pulizia
nettoyer,detergere
nourrissant,nutriente
nuances,sfumature
nutritifs,nutritivi
odorant,profumato
ombreur,sfumino
onctueuse,vellutata
ongle,unghia
Only,Only
ophtalmologique,oftalmologico
orteils,"dita dei piedi"
pack,confezione
packaging,packaging
paillet,glitterato
paillettes,glitter
palette,palette
parer,impreziosire
parfum,profumo
patte,zampa
paume,palmo
paumettes,palme
paupière,palpebra
peau,pelle
peeling,peeling
ph,ph
pigment,pigmento
pince,pinza
pinceau,pennello
pipette,pipetta
poignet,polso
poils,peli
Polanski,Polanski
pollution,inquinamento
pomettes,zigomi
Poppy,Poppy
pores,pori
Possessed,Possessed
poudre,cipria
propre,pulito
pulpeuse,polposa
Queen,Queen
rabattre,abbassare
racine,radice
radieux,radioso
raffermissant(3,rassodante(3
ration,dose
rebondie,rimpolpata
recourbe,piega
recourbe-cils,piegaciglia
regorgé,rinvigorito
rehausser,rinforzare
repulpant,rimpolpante
ridules,linee
rincer,risciacquare
rouge,rossetto
rougeur,rossore
sacs,borse
Sailor,Sailor
satin,raso
Screen,Screen
sculpter,scolpire
sebum,sebo
Sephora,Sephora
serviette,panno
sérum,siero
shampooing,shampoo
Sheer,Sheer
shine,shine
Silver,Silver
smokey,smokey
smoky,smoky
soin,cura
sourcil,sopracciglio
soyeux,setoso
SPF,SPF
SPF15,SPF15
spray,spray
stars,stars
Stay,Stay
Step,Step
Stray,Stray
Stylo,Matita
sulfates,solfati
SUN,SUN
Sur-Hydratant,Ultra-Idratante
Sur-Hydratante,Ultra-idratante
tapoter,picchiettare
teint,colorito
tenue,tenuta
Test,Test
texture,texture
tiraillements,"la pelle che tira"
tirer,tirare
tissu,tessuto
toilette,toilette
tonifié,tonificato
topcoat,topcoat
top-coat,top-coat
tremper,bagnare
T-Sonic,T-Sonic
ultra-douce,ultra-dolce
ultra-glossy,"ultra glossy"
ultra-hydratante,"ultra idratante"
ultra-lisse,"ultra levigata"
Ultra-Nourrissante,"Ultra nutriente"
utilisatrices,clienti
utiliser,utilizzare
vaporisateur,vaporizzatore
vaporisez,vaporizza
vernis,smalto
Virole,Impugnatura
visage,viso
volontaires,volontarie
volume,volume
volumineux,voluminoso
waterproof,waterproof
XL,XL
y,y
Y245,Y245
Y315,Y315
Y325,Y325
Y335,Y335
Y35,Y35
yeux,occhi
zigzag,zig-zag
zone,zona
SEPHORA,SEPHORA
"MAKE UP FOR EVER","MAKE UP FOR EVER"
"TOO FACED","TOO FACED"
BENEFIT,BENEFIT
NARS,NARS
"LIPSTICK QUEEN","LIPSTICK QUEEN"
TONYMOLY,TONYMOLY
PTR,PTR
FOREO,FOREO
SLEEK,SLEEK
BURBERRY,BURBERRY
"MARC JACOBS BEAUTY","MARC JACOBS BEAUTY"
REXALINE,REXALINE
STRIVECTIN,STRIVECTIN
"VITA LIBERATA","VITA LIBERATA"
"MAKE UP ERASER","MAKE UP ERASER"
"MERCI HANDY","MERCI HANDY"
"NARCISO RODRIGUEZ","NARCISO RODRIGUEZ"
"THE CURVE","THE CURVE"
"JIMMY CHOO","JIMMY CHOO"
"CALVIN KLEIN","CALVIN KLEIN"
CHLOE,CHLOE
"ISSEY MIYAKE","ISSEY MIYAKE"
ESCADA,ESCADA
fini,finish
raffermissant,rassodante
enfants,bambini
