<?php

use FilesStorage\S3FilesStorage;

class S3FilesStorageTest extends PHPUnit_Framework_TestCase {

    /**
     * @var S3FilesStorage
     */
    private $fs;

    public function setUp() {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->fs = new S3FilesStorage();
    }

    /**
     * @test
     */
    public function test_get_cache_package_bucket_name() {
        $filePath = __DIR__ . '/../../../support/files/docx/WhiteHouse.docx';
        $sha1     = sha1_file( $filePath );
        $lang     = 'it-IT';

        $cacheBucketName = $this->fs->getCachePackageBucketName( $sha1, $lang );

        $this->assertTrue( strlen( $cacheBucketName ) === 62 );
    }

    /**
     * @test
     */
    public function test_upload_a_package_into_a_bucket() {
        $filePath        = __DIR__ . '/../../../support/files/txt/hello.txt';
        $xliffPath       = __DIR__ . '/../../../support/files/xliff/file-with-hello-world.xliff';
        $xliffPathTarget = __DIR__ . '/../../../support/files/xliff/file-with-hello-world.xliff';

        copy($xliffPath, $xliffPathTarget); // I copy the original xliff file because then

        $sha1 = sha1_file( $filePath );
        $lang = 'it-IT';

        $this->assertTrue( $this->fs->makeCachePackage( $sha1, $lang, $filePath, $xliffPathTarget ) );
    }
}