<?php
$languages = array(
    "Afrikaans" => "Afrikaans"
    , "Albanian" => "Albanian"
    , "Arabic" => "Arabic"
    , "Armenian" => "Armenian"
    , "Basque" => "Basque (Euskera)"
    , "Bengali" => "Bengali"
    , "Bielarus" => "Belarusian"
    , "Bosnian" => "Bosnian"
    , "Breton" => "Breton"
    , "Bulgarian" => "Bulgarian"
    , "Burmese" => "Burmese"
    , "Catalan" => "Catalan"
    , "Chinese" => "Chinese Simplified"
    , "Chinese Traditional" => "Chinese Traditional"
    , "Classical Greek" => "Classical Greek"
    , "Croatian" => "Croatian"
    , "Czech" => "Czech"
    , "Danish" => "Danish"
    , "Dutch" => "Dutch"
    , "English" => "English ( GB )"
    , "English US" => "English ( USA )"
    , "Esperanto" => "Esperanto"
    , "Estonian" => "Estonian"
    , "Faroese" => "Faroese"
    , "Finnish" => "Finnish"
    , "Flemish" => "Dutch ( Belgium )"
    , "French" => "French ( France )"
    , "Galician" => "Galician"
    , "German" => "German"
    , "Georgian" => "Georgian"
    , "Greek" => "Greek"
    , "Haitian Creole French" => "Haitian Creole French"
    , "Hawaiian" => "Hawaiian"
    , "Hebrew" => "Hebrew"
    , "Hindi" => "Hindi"
    , "Hungarian" => "Hungarian"
    , "Icelandic" => "Icelandic"
    , "Indonesian" => "Indonesian"
    , "Irish Gaelic" => "Irish Gaelic"
    , "Italian" => "Italian"
    , "Japanese" => "Japanese"
    , "Jamaican Creole English" => "Jamaican Creole English"
    , "Javanese" => "Javanese"
    , "Kazakh" => "Kazakh"
    , "Korean" => "Korean"
    , "Khmer" => "Khmer"
    , "Kirundi" => "Kirundi"
    , "Kurdish" => "Kurdish Kurmanji ( Latin )"
    , "Kurdish Sorani" => "Kurdish Sorani ( Arabic )"
    , "Latin" => "Latin"
    , "Latvian" => "Latvian"
    , "Lithuanian" => "Lithuanian"
    , "Macedonian" => "Macedonian"
    , "Malay" => "Malay"
    , "Maltese" => "Maltese"
    , "Maori" => "Maori"
    , "Mongolian" => "Mongolian"
    , "Nepali" => "Nepali"
    , "Norwegian" => "Norwegian"
    , "Pakistani" => "Urdu"
    , "Panjabi" => "Punjabi"
    , "Pashto" => "Pashto"
    , "Persian" => "Farsi"
    , "Polish" => "Polish"
    , "Portuguese Brazil" => "Portuguese ( Brazil )"
    , "Portuguese" => "Portuguese ( Portugal )"
    , "Quebecois" => "French ( Canada )"
    , "Quechua" => "Quechua"
    , "Romanian" => "Romanian"
    , "Russian" => "Russian"
    , "Scots Gaelic" => "Scots Gaelic"
    , "Serbian" => "Serbian"
    , "Sinhala" => "Sinhala"
    , "Slovak" => "Slovak"
    , "Slovenian" => "Slovenian"
    , "Somali" => "Somali"
    , "Spanish" => "Spanish ( Spain )"
    , "Spanish Latin America" => "Spanish ( Latin America )"
    , "Swahili" => "Swahili"
    , "Swedish" => "Swedish"
    , "Swiss German" => "German ( Switzerland )"
    , "Tagalog" => "Tagalog"
    , "Tajik" => "Tajik"
    , "Tamil" => "Tamil"
    , "Thai" => "Thai"
    , "Tibetan" => "Tibetan"
    , "Turkish" => "Turkish"
    , "Ukrainian" => "Ukrainian"
    , "Vietnamese" => "Vietnamese"
    , "Welsh" => "Welsh"
    , "Tigrinya" => "Tigrinya"
    ,'Azerbaijani' => 'Azerbaijani'
    ,'Luxembourgish' => 'Luxembourgish'
    ,'Uzbek' => 'Uzbek'
    ,'Morisyen' => 'Morisyen'
    ,'Kyrgyz' => 'Kyrgyz'
    ,'Tswana' => 'Tswana'
    ,'Bahamas Creole English' => 'Bahamas Creole English'
    ,'Bajan' => 'Bajan'
    ,'Bemba' => 'Bemba'
    ,'Guyanese Creole English' => 'Guyanese Creole English'
    ,'Virgin Islands Creole English' => 'Virgin Islands Creole English'
    ,'Lao' => 'Lao'
    ,'Chamorro' => 'Chamorro'
    ,'Saint Lucian Creole French' => 'Saint Lucian Creole French'
    ,'Inuktitut, Greenlandic' => 'Inuktitut, Greenlandic'
    ,'Antigua and Barbuda Creole English' => 'Antigua and Barbuda Creole English'
    ,'Seselwa Creole French' => 'Seselwa Creole French'
    ,'Shona' => 'Shona'
    ,'Nyanja' => 'Nyanja'
    ,'Kinyarwanda' => 'Kinyarwanda'
    ,'Turkmen' => 'Turkmen'
    ,'Papiamentu' => 'Papiamentu'
    ,'Kabuverdianu' => 'Kabuverdianu'
    ,'Maldivian' => 'Maldivian'
    ,'Vincentian Creole English' => 'Vincentian Creole English'
    ,'Amharic' => 'Amharic'
    ,'Malagasy' => 'Malagasy'
    ,'Tok Pisin' => 'Tok Pisin'
    ,'Dzongkha' => 'Dzongkha'
    ,'Grenadian Creole English' => 'Grenadian Creole English'
    ,'Sotho, Southern' => 'Sotho, Southern'
    ,'Hausa' => 'Hausa'
    ,'Bislama' => 'Bislama'
    ,'Tongan' => 'Tongan'
    ,'Samoan' => 'Samoan'
    ,'Comorian, Ngazidja' => 'Comorian, Ngazidja'
    ,'Palauan' => 'Palauan'
        )
?>
