<?php

namespace Model\Jobs;

class LexiQaAndTagProjectionLanguages
{
    public static array $lexiQaAllowedLanguages = [
        'af-ZA',
        'sq-AL',
        'ar-SA',
        'hy-AM',
        'as-IN',
        'az-AZ',
        'fr-BE',
        'bn-IN',
        'be-BY',
        'bs-BA',
        'bg-BG',
        'my-MM',
        'ca-ES',
        'zh-CN',
        'zh-TW',
        'zh-HK',
        'hr-HR',
        'cs-CZ',
        'da-DK',
        'nl-NL',
        'en-GB',
        'en-US',
        'en-AU',
        'en-CA',
        'en-IN',
        'en-IE',
        'en-NZ',
        'en-SG',
        'et-EE',
        'fi-FI',
        'nl-BE',
        'fr-FR',
        'fr-CA',
        'fr-CH',
        'de-DE',
        'ka-GE',
        'el-GR',
        'gu-IN',
        'hi-IN',
        'hu-HU',
        'id-ID',
        'it-IT',
        'ja-JP',
        'jv-ID',
        'ha-NG',
        'he-IL',
        'ht-HT',
        'kk-KZ',
        'rn-BI',
        'ko-KR',
        'ky-KG',
        'lv-LV',
        'lt-LT',
        'mk-MK',
        'ms-MY',
        'mr-IN',
        'ne-NP',
        'nb-NO',
        'fa-IR',
        'pl-PL',
        'pt-PT',
        'pt-BR',
        'ro-RO',
        'ru-RU',
        'sr-Latn-RS',
        'sr-Cyrl-RS',
        'si-LK',
        'sk-SK',
        'sl-SI',
        'es-ES',
        'es-CO',
        'es-MX',
        'es-US',
        'es-419',
        'sw-KE',
        'sv-SE',
        'de-CH',
        'tl-PH',
        'ta-LK',
        'ta-IN',
        'th-TH',
        'tr-TR',
        'uk-UA',
        'ur-PK',
        'uz-UZ',
        'vi-VN'

    ];

    public static array $tagProjectionAllowedLanguages = [
        'en-de' => 'English - German',
        'en-es' => 'English - Spanish',
        'en-fr' => 'English - French',
        'en-it' => 'English - Italian',
        'en-pt' => 'English - Portuguese',
        'en-ru' => 'English - Russian',
        'en-cs' => 'English - Czech',
        'en-nl' => 'English - Dutch',
        'en-fi' => 'English - Finnish',
        'en-pl' => 'English - Polish',
        'en-da' => 'English - Danish',
        'en-sv' => 'English - Swedish',
        'en-el' => 'English - Greek',
        'en-hu' => 'English - Hungarian',
        'en-lt' => 'English - Lithuanian',
        'en-ja' => 'English - Japanese',
        'en-et' => 'English - Estonian',
        'en-sk' => 'English - Slovak',
        'en-bg' => 'English - Bulgarian',
        'en-bs' => 'English - Bosnian',
        'en-ar' => 'English - Arabic',
        'en-ca' => 'English - Catalan',
        'en-zh' => 'English - Chinese',
        'en-he' => 'English - Hebrew',
        'en-hr' => 'English - Croatian',
        'en-id' => 'English - Indonesian',
        'en-is' => 'English - Icelandic',
        'en-ko' => 'English - Korean',
        'en-lv' => 'English - Latvian',
        'en-mk' => 'English - Macedonian',
        'en-ms' => 'English - Malay',
        'en-mt' => 'English - Maltese',
        'en-nb' => 'English - Norwegian Bokmål',
        'en-nn' => 'English - Norwegian Nynorsk',
        'en-ro' => 'English - Romanian',
        'en-sl' => 'English - Slovenian',
        'en-sq' => 'English - Albanian',
        'en-sr' => 'English - Montenegrin',
        'en-th' => 'English - Thai',
        'en-tr' => 'English - Turkish',
        'en-uk' => 'English - Ukrainian',
        'en-vi' => 'English - Vietnamese',
        'de-it' => 'German - Italian',
        'de-fr' => 'German - French',
        'de-cs' => 'German - Czech',
        'fr-it' => 'French - Italian',
        'fr-nl' => 'French - Dutch',
        'it-es' => 'Italian - Spanish',
        'da-sv' => 'Danish - Swedish',
        'nl-pt' => 'Dutch - Portuguese',
        'nl-fi' => 'Dutch - Finnish',
        'zh-en' => 'Chinese - English',
        'sv-da' => 'Swedish - Danish',
        'cs-de' => 'Czech - German',
    ];
}
